FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY . .

RUN dotnet restore "HotofLobbyServer.Api/HotofLobbyServer.Api.csproj"

RUN dotnet publish "HotofLobbyServer.Api/HotofLobbyServer.Api.csproj" \
    -c Release \
    -o /app/publish


FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "HotofLobbyServer.Api.dll"] 